### ISSUE TITLE
No Internet using NAT instance

### ISSUE THREAD

**Issue by dcardellino** [garutilorenzo/oracle-cloud-terraform-examples#1]
Hi,

I tried to use your examples setting up a nat instance and a additional private instance as in your examples here:

https://github.com/garutilorenzo/oracle-cloud-terraform-examples/blob/master/examples/main.tf

But when I connect to the simple-instance and try to install some packages, I have no access to the internet?

I copied your code 1:1.

Do you have any idea?

**Comment by garutilorenzo** [comment]
Hi @dcardellino,

same problem for the instances of the instance pool?

**Comment by dcardellino** [comment]
@garutilorenzo  I will give it a tray in the afternoon :-) I think I used Ubuntu 22.04 and there is no firewalld installed. Therefore the NAT rules were not applied.
But I will let you know as soon as I know it ;-)

**Comment by garutilorenzo** [comment]
The problem was the nat rules on the nat instances. The interface used for setting up the nat rules was hardcoded, now it's a variable. First the script will find the default gw interface name , then applies the nat rules.
